export const FETCH_ANIMALS = 'FETCH_ANIMALS';
export const FETCH_ANIMAL_BY_ID_SUCCESS = 'FETCH_ANIMAL_BY_ID_SUCCESS';
export const FETCH_ANIMAL_BY_ID_INIT = 'FETCH_ANIMAL_BY_ID_INIT';
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_ASSO_SUCCESS = 'REGISTER_ASSO_SUCCESS';
export const REGISTER_ASSO_FAILURE = 'REGISTER_ASSO_FAILURE';

export const FETCH_ASSOCIATION_BY_ID_INIT = 'FETCH_ASSOCIATION_BY_ID_INIT';
export const FETCH_ASSOCIATION_BY_ID_SUCCESS = 'FETCH_ASSOCIATION_BY_ID_SUCCESS';
export const FETCH_ASSOS_SUCCESS = 'FETCH_ASSOS_SUCCESS';

export const UPDATE_ANIMAL_SUCCESS = 'UPDATE_ANIMAL_SUCCESS';
export const UPDATE_ANIMAL_FAIL = 'UPDATE_ANIMAL_FAIL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOGIN_ASSO_SUCCESS = 'LOGIN_ASSO_SUCCESS';
export const LOGIN_ASSO_FAILURE = 'LOGIN_ASSO_FAILURE';
export const LOGOUT_ASSO = 'LOGOUT_ASSO';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const EDIT_ASSO_SUCCESS = 'EDIT_ASSO_SUCCESS';
export const EDIT_ASSO_FAILURE = 'EDIT_ASSO_FAILURE';

export const FETCH_RACE_SUCCESS = 'FETCH_RACE_SUCCESS';

export const FETCH_SEX_SUCCESS = 'FETCH_SEX_SUCCESS';

export const FETCH_COATS_SUCCESS = 'FETCH_COATS_SUCCESS';
export const FETCH_COLOR_SUCCESS = 'FETCH_COLOR_SUCCESS';
export const FETCH_SIZE_SUCCESS = 'FETCH_SIZE_SUCCESS';
export const FETCH_SPECIE_SUCCESS = 'FETCH_SPECIE_SUCCESS';

export const CREATE_ANIMAL_SUCCESS = 'CREATE_ANIMAL_SUCCESS';
