vich_uploader:
    db_driver: orm

    mappings:
       animals_images:
           uri_prefix: /images/animaux
           upload_destination: '%kernel.project_dir%/public/images/animaux'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
